<?php
/** op-layout-onepiece:/header.phtml
 *
 * @creation  2017-09-07
 * @version   1.0
 * @package   op-layout-onepiece
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

//	...
OP()->WebPack()->Auto('css/header.css');

?>
<header>
	<a href="<?= OP::MetaPath('app:/', true) ?>"><img src="/img/icon.png"/></a>
	<div>
		<a href="<?= OP::MetaPath('app:/', true) ?>"><span>onepiece-framework.com</span></a>
	</div>
</header>
