<?php
/**
 * layout-onepiece:/header.phtml
 *
 * @creation  2017-09-07
 * @version   1.0
 * @package   layout-onepiece
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

/** Used class.
 *
 */

/* @var $app \OP\UNIT\App */
?>
<header>
	<a href="<?= $app->URL('app:/') ?>"><img src="/img/icon.png"/></a>
	<div>
		<a href="<?= $app->URL('app:/') ?>"><span>onepiece-framework.com</span></a>
	</div>
</header>
