<?php
/**
 * layout-onepiece:/html.phtml
 *
 * @creation  2017-09-07
 * @version   1.0
 * @package   layout-onepiece
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

/** Used class.
 *
 */

/* @var $app    \OP\UNIT\App */
/* @var $content string      */
?>
<!doctype html>
<html lang="<?= Env::Lang() ?>">
	<head>
		<?= $app->Template('layout/head.phtml') ?>
	</head>
	<body id="body" class="body">
		<div id="head-area">
			<?= $app->Template('header.phtml') ?>
		</div>
		<div id="body-area" class="body-area">
			<div id="content-area" class="content-area">
				<?= $content ?>
			</div>
		</div>
		<div id="foot-area">
			<?= $app->Template('footer.phtml') ?>
		</div>
	</body>
</html>
