<?php
/** op-layout-onepiece:/html.phtml
 *
 * @creation  2017-09-07
 * @version   1.0
 * @package   op-layout-onepiece
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 * @created   2019-02-23
 */
namespace OP;

/** Used class.
 *
 */

?>
<!doctype html>
<html lang="<?= Env::Lang() ?>">
	<head>
		<?= Template('layout/head.phtml') ?>
	</head>
	<body id="body" class="body" role="document">
		<div id="head-area">
			<?= Template('header.phtml') ?>
		</div>
		<div id="body-area" class="body-area">
			<div id="content-area" class="content-area">
				<?= Content(); ?>
			</div>
		</div>
		<div id="foot-area">
			<?= Template('footer.phtml') ?>
		</div>
	</body>
</html>
